spring:
  datasource:
    url : jdbc:mysql://localhost:3306/filedb
    username : root
    password : root1234
  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true
    properties :
      format_sql : true
